#!/bin/bash

echo "creating page ${1}"
mkdir -p "./src/pages/${1}"
touch "./src/pages/${1}/${1}.tsx" 
touch "./src/pages/${1}/${1}.module.css" 
touch "./src/pages/${1}/${1}.test.tsx"
echo "import React from 'react';" >> "./src/pages/${1}/${1}.test.tsx"
echo "import React from 'react';" >> "./src/pages/${1}/${1}.tsx"
echo "import ${1} from './${1}.module.css';" >> "./src/pages/${1}/${1}.tsx"
#print "\n" >> "./src/pages/${1}/${1}.tsx"
echo "const ${1^}: React.FC = ():JSX.Element => {" >> "./src/pages/${1}/${1}.tsx"
echo " return (" >> "./src/pages/${1}/${1}.tsx"
echo "            <>" >> "./src/pages/${1}/${1}.tsx"
echo "               <h1>Hello from ${1^} page </h1>" >> "./src/pages/${1}/${1}.tsx"
echo "            </>" >> "./src/pages/${1}/${1}.tsx"
echo "        )" >> "./src/pages/${1}/${1}.tsx"
echo "}" >> "./src/pages/${1}/${1}.tsx"
echo "export default ${1^};" >> "./src/pages/${1}/${1}.tsx"
echo "page has been created"
